import { GetStaticPaths } from 'next'
import Head from 'next/head'
import { sanityClient } from '../../sanity'

const BlogPost = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>BlogPostPage</h1>
      </main>
    </div>
  )
}

export default BlogPost

export const getStaticPaths: GetStaticPaths = async () => {
  const query = `*[_type == "post" ]{
    _id,
    slug {
    current
  }
  }`

  const posts = await sanityClient.fetch(query)

  const paths = posts.map((post: any) => ({
    params: {
      slug: post.slug.current
    }
  }))

  return {
    paths,
    fallback: "blocking"
  }
}