import { GetStaticProps } from 'next'
import Head from 'next/head'
import { sanityClient } from '../../sanity'
import { Post } from '../../types'

interface Props {
  posts: Post
}

const Blog = ({ posts }: Props) => {
  console.log(posts)
  return (
    <div>
      <Head>
        <title>Blog - Kai Rekdahl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='max-w-7xl mx-auto'>
        <div className='m-10'>
          <h1 className='text-4xl'>Blog</h1>
          <div className='bg-stone-50 bg-opacity-10'>hello world</div>
        </div>
      </main>
    </div>
  )
}

export default Blog

export const getStaticProps: GetStaticProps = async () => {
  const query = `*[_type == "post" ]{
    _id,
    title,
    description
  }`

  const posts = await sanityClient.fetch(query)

  return {
    props: {
      posts
    },
    revalidate: 86400
  }
}