import Head from 'next/head'
import Image from 'next/image'

import { IoLogoFacebook, IoLogoInstagram, IoMail } from "react-icons/io5";

const About = () => {
  return (
    <div>
      <Head>
        <title>About - Kai Rekdahl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='max-w-7xl mx-auto'>
        <div className='m-10 px-6 py-10 space-y-10 flex flex-col items-center bg-stone-800 bg-opacity-50 rounded-lg shadow-lg'>
          <span className='text-center'>
            <Image className='rounded-full' width={300} height={300} src='/static/images/kai.png' alt=''/>
            <h1 className='text-3xl text-stone-200'>Kai Rekdahl</h1>
            <p className='text-stone-500'>i take pictures</p>
          </span>
          <p className='sm:w-4/5 sm:text-xl text-center text-neutral-400'>
            I&apos;m an aspiring photographer and I&apos;ve been interested in photography since 2018.
            Traveling to Japan and the United States several times, as well as living on Guam, 
            I became interested in landscaping and nature photography.
          </p>
          <p className='sm:w-4/5 sm:text-xl text-center text-neutral-400'>
            I love taking photos of environments and landscapes that stick out to me and I like utilizing natural light, most notably the sun.
            Recently, I&apos;ve been taking interest in video projects and filmmaking and hope to gain experience in that field.
          </p>
          <div className='flex flex-col space-y-2 items-center'>
            <a className='p-1 gap-2 flex items-center hover:bg-neutral-100 hover:bg-opacity-30 rounded-md' href='https://www.instagram.com/kai.rekdahl/' target='_blank' rel='noreferrer'>
              <IoLogoInstagram size={20} />
              kai.rekdahl
            </a>
            <a className='p-1 gap-2 flex items-center hover:bg-neutral-100 hover:bg-opacity-30 rounded-md' href='https://www.facebook.com/kaicarlson.rekdahl' target='_blank' rel='noreferrer'>
              <IoLogoFacebook size={20} />
              kaicarlson.rekdahl
            </a>
            <div className='p-1 gap-2 flex items-center'>
              <IoMail size={20} />
              kai.rekdahl@email.com
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export default About