import Head from 'next/head'
import { sanityClient, urlFor } from '../sanity'
import { GetStaticProps } from 'next'
import Image from 'next/image';
import { Photo } from '../types';
import { useState } from 'react';

interface Props {
  gallery: Photo[];
}


const Photography = ({ gallery }: Props) => {
  const randomPhoto = Math.floor(Math.random()*gallery.length)
  const [photo, setPhoto] = useState(randomPhoto)

  const changePhoto = (i: number) => {
    const n = gallery.length
    setPhoto((prev) => (((prev + i) % n + n) % n)) 
  }

  return (
    <div>
      <Head>
        <title>Photography - Kai Rekdahl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='relative w-screen h-screen bg-black'>
          <Image key={gallery[photo]._key} layout='fill' objectFit='contain' src={urlFor(gallery[photo].asset._ref)} alt="" />

          {/* Gallery Navigation Menu */}
          <span className='absolute z-10 w-screen h-screen flex justify-between'>
            <button onClick={() => changePhoto(-1)} className='flex-1 focus:outline-none' />
            <button onClick={() => changePhoto(1)} className='flex-1 focus:outline-none' />
          </span>
        </div>
      </main>
    </div>
  )
}

export default Photography

// export const getStaticProps: GetStaticProps = async () => {
//   const query = `*[_type == "gallery" ][0]{
//     images
//   }`

//   const gallery = await sanityClient.fetch(query)
  

//   return {
//     props: {
//       gallery: gallery.images,
//     },
//     revalidate: 86400,
//   }
// }